// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TET_BET;

namespace TET_BET.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211217180737_FirstVersionDB")]
    partial class FirstVersionDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("TET_BET.Models.DBAccountDetails", b =>
                {
                    b.Property<int>("accountDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("accountBalance")
                        .HasColumnType("float");

                    b.Property<DateTime>("dateRegistered")
                        .HasColumnType("datetime");

                    b.HasKey("accountDetailsID");

                    b.ToTable("DBAccountDetails");
                });

            modelBuilder.Entity("TET_BET.Models.DBBet", b =>
                {
                    b.Property<int>("betID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("betName")
                        .HasColumnType("text");

                    b.Property<int?>("betTypeID")
                        .HasColumnType("int");

                    b.HasKey("betID");

                    b.HasIndex("betTypeID");

                    b.ToTable("DBBet");
                });

            modelBuilder.Entity("TET_BET.Models.DBBetType", b =>
                {
                    b.Property<int>("betTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("betTypeName")
                        .HasColumnType("text");

                    b.Property<int?>("sportID")
                        .HasColumnType("int");

                    b.HasKey("betTypeID");

                    b.HasIndex("sportID");

                    b.ToTable("DBBetType");
                });

            modelBuilder.Entity("TET_BET.Models.DBBettingEventStatus", b =>
                {
                    b.Property<int>("bettingEventStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("bettingEventStatusDescription")
                        .HasColumnType("text");

                    b.Property<string>("bettingEventStatusMessage")
                        .HasColumnType("text");

                    b.HasKey("bettingEventStatusID");

                    b.ToTable("DBBettingEventStatus");
                });

            modelBuilder.Entity("TET_BET.Models.DBBettingTicket", b =>
                {
                    b.Property<int>("bettingTicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("accountDetailsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("bettingTicketDate")
                        .HasColumnType("datetime");

                    b.Property<float>("bettingTicketSum")
                        .HasColumnType("float");

                    b.HasKey("bettingTicketID");

                    b.HasIndex("accountDetailsID");

                    b.ToTable("DBBettingTicket");
                });

            modelBuilder.Entity("TET_BET.Models.DBEvent", b =>
                {
                    b.Property<int>("eventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("bettingEventDate")
                        .HasColumnType("datetime");

                    b.Property<string>("bettingEventLocation")
                        .HasColumnType("text");

                    b.Property<int?>("bettingEventStatusID")
                        .HasColumnType("int");

                    b.Property<int>("sportID")
                        .HasColumnType("int");

                    b.HasKey("eventID");

                    b.HasIndex("bettingEventStatusID");

                    b.HasIndex("sportID");

                    b.ToTable("DBEvent");
                });

            modelBuilder.Entity("TET_BET.Models.DBFootballEvent", b =>
                {
                    b.Property<int>("footballEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("footballEventID");

                    b.ToTable("DBFootballEvent");
                });

            modelBuilder.Entity("TET_BET.Models.DBSport", b =>
                {
                    b.Property<int>("sportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("sportName")
                        .HasColumnType("text");

                    b.HasKey("sportID");

                    b.ToTable("DBSport");
                });

            modelBuilder.Entity("TET_BET.Models.DBTransaction", b =>
                {
                    b.Property<int>("transactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("accountDetailsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("transactionDate")
                        .HasColumnType("datetime");

                    b.Property<float>("transactionSum")
                        .HasColumnType("float");

                    b.HasKey("transactionID");

                    b.HasIndex("accountDetailsID");

                    b.ToTable("DBTransaction");
                });

            modelBuilder.Entity("TET_BET.Models.DBUser", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("accountDetailsID")
                        .HasColumnType("int");

                    b.Property<string>("userEmail")
                        .HasColumnType("text");

                    b.Property<string>("userPassword")
                        .HasColumnType("text");

                    b.HasKey("userID");

                    b.HasIndex("accountDetailsID")
                        .IsUnique();

                    b.ToTable("DBUser");
                });

            modelBuilder.Entity("TET_BET.Models.DBUserBet", b =>
                {
                    b.Property<int>("userBetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("betID")
                        .HasColumnType("int");

                    b.Property<int?>("bettingTicketID")
                        .HasColumnType("int");

                    b.Property<int?>("dbEventeventID")
                        .HasColumnType("int");

                    b.Property<int>("eventID")
                        .HasColumnType("int");

                    b.Property<float>("oddValue")
                        .HasColumnType("float");

                    b.HasKey("userBetID");

                    b.HasIndex("betID");

                    b.HasIndex("bettingTicketID");

                    b.HasIndex("dbEventeventID");

                    b.ToTable("DBUserBet");
                });

            modelBuilder.Entity("TET_BET.Models.DBBet", b =>
                {
                    b.HasOne("TET_BET.Models.DBBetType", "betType")
                        .WithMany("betsList")
                        .HasForeignKey("betTypeID");

                    b.Navigation("betType");
                });

            modelBuilder.Entity("TET_BET.Models.DBBetType", b =>
                {
                    b.HasOne("TET_BET.Models.DBSport", "sport")
                        .WithMany()
                        .HasForeignKey("sportID");

                    b.Navigation("sport");
                });

            modelBuilder.Entity("TET_BET.Models.DBBettingTicket", b =>
                {
                    b.HasOne("TET_BET.Models.DBAccountDetails", "accountDetails")
                        .WithMany("bettingTicketsList")
                        .HasForeignKey("accountDetailsID");

                    b.Navigation("accountDetails");
                });

            modelBuilder.Entity("TET_BET.Models.DBEvent", b =>
                {
                    b.HasOne("TET_BET.Models.DBBettingEventStatus", "bettingEventStatus")
                        .WithMany()
                        .HasForeignKey("bettingEventStatusID");

                    b.HasOne("TET_BET.Models.DBSport", "sport")
                        .WithMany()
                        .HasForeignKey("sportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bettingEventStatus");

                    b.Navigation("sport");
                });

            modelBuilder.Entity("TET_BET.Models.DBTransaction", b =>
                {
                    b.HasOne("TET_BET.Models.DBAccountDetails", "accountDetails")
                        .WithMany("transactionsList")
                        .HasForeignKey("accountDetailsID");

                    b.Navigation("accountDetails");
                });

            modelBuilder.Entity("TET_BET.Models.DBUser", b =>
                {
                    b.HasOne("TET_BET.Models.DBAccountDetails", "accountDetails")
                        .WithOne("user")
                        .HasForeignKey("TET_BET.Models.DBUser", "accountDetailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("accountDetails");
                });

            modelBuilder.Entity("TET_BET.Models.DBUserBet", b =>
                {
                    b.HasOne("TET_BET.Models.DBBet", "bet")
                        .WithMany()
                        .HasForeignKey("betID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TET_BET.Models.DBBettingTicket", "bettingTicket")
                        .WithMany("bettingTicketBetsList")
                        .HasForeignKey("bettingTicketID");

                    b.HasOne("TET_BET.Models.DBEvent", "dbEvent")
                        .WithMany()
                        .HasForeignKey("dbEventeventID");

                    b.Navigation("bet");

                    b.Navigation("bettingTicket");

                    b.Navigation("dbEvent");
                });

            modelBuilder.Entity("TET_BET.Models.DBAccountDetails", b =>
                {
                    b.Navigation("bettingTicketsList");

                    b.Navigation("transactionsList");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TET_BET.Models.DBBetType", b =>
                {
                    b.Navigation("betsList");
                });

            modelBuilder.Entity("TET_BET.Models.DBBettingTicket", b =>
                {
                    b.Navigation("bettingTicketBetsList");
                });
#pragma warning restore 612, 618
        }
    }
}
