// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TET_BET;

namespace TET_BET.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("TET_BET.Models.DBUser", b =>
                {
                    b.Property<int>("_userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("_dummy")
                        .HasColumnType("text");

                    b.Property<string>("_userEmail")
                        .HasColumnType("text");

                    b.Property<string>("_userPassword")
                        .HasColumnType("text");

                    b.HasKey("_userID");

                    b.ToTable("DBUser");
                });
#pragma warning restore 612, 618
        }
    }
}
